### ISSUE TITLE
The server cannot handle multiple connections at the same time

### ISSUE THREAD

**Issue by DDorch** [DDorch/Scada_DDorch#16]
If one client is connected to the server, no one can connect to the server until the first connection has been closed.

**Comment by DDorch** [comment]
I followed the code proposed above but I get this error on Windows:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\DocDD\OnCld\Apps\WPy\python-3.7.0.amd64\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\DocDD\OnCld\Apps\WPy\python-3.7.0.amd64\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\DocDD\OnCld\Apps\WPy\python-3.7.0.amd64\lib\socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "C:\DocDD\OnCld\Apps\WPy\python-3.7.0.amd64\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\DocDD\OnCld\Apps\WPy\python-3.7.0.amd64\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] Une opération a été tentée sur autre chose qu’un socket
```

**Comment by DDorch** [comment]
In fact, in it's current configuration, the server does'nt need a persistent connection. A REST API should be a better solution and could resolve the problem of concurrent connections.
